#!/usr/bin/env node

 /* eslint-disable no-console */

'use strict' // eslint-disable-line node/shebang

const server = require('.')

const [, , method] = process.argv
let p

switch (method) {
case 'start':
  p = server.start()
  break
case 'stop':
  p = server.stop()
  break
case 'restart':
  p = server.restart()
  break
case 'status':
  p = server.isPortOpen().then(open => {
    if (open) {
      console.log('started')
    } else {
      console.log('stopped')
    }
  })
  break
default:
  p = Promise.reject(new Error('Valid commands are start/stop/restart/status.'))
}

p.catch(err => console.error(err))
